### ISSUE TITLE
Model stays active even after removing it from prompt

### ISSUE THREAD

**Issue by FNSpd** [KohakuBlueleaf/a1111-sd-webui-lycoris#19] opened 2023-04-30 06:50 UTC
Basically, what the title says. Try to add model to the prompt, generate picture, remove lyco part, and model will still have effect on image

**Comment by poko3347** [comment] 2023-04-30 23:20
This issue occurs frequently.

**Comment by KohakuBlueleaf** [comment] 2023-05-01 03:43
@FNSpd @poko3347 I also cannot totally avoid this issue
But I have test lot of pattern (like 2 lyco -> 1 lyco -> 2lyco -> 0 lyco) and it should be resolved
Can you two let me know which commit you are using? (the sd-webui commit)
Or you guys are using vladmandic's automatic?

**Comment by I-ShadowStar** [comment] 2023-05-01 05:15
Came here to look for troubleshooting and this happened to me recently. I am using the UX fork.
https://github.com/anapnoe/stable-diffusion-webui-ux

**Comment by FNSpd** [comment] 2023-05-01 08:50
> @FNSpd @poko3347 I also cannot totally avoid this issue But I have test lot of pattern (like 2 lyco -> 1 lyco -> 2lyco -> 0 lyco) and it should be resolved Can you two let me know which commit you are using? (the sd-webui commit) Or you guys are using vladmandic's automatic?

I'm using latest commit for both A1111 and extension

**Comment by RayHell** [comment] 2023-05-03 17:24
Same issue for me I'm on the latest auto1111

**Comment by BigBlueGX** [comment] 2023-05-04 16:33
Happens to me as well. It's a common issue with the Loras that I train. Switching checkpoint models resolves this

**Comment by KohakuBlueleaf** [comment] 2023-05-04 16:37
Yeah it is a issue in the weight backup mechanism
But I cannot find which part goes wrong...

**Comment by FNSpd** [comment] 2023-05-06 12:06
Using standart LoRA without LyCORIS seems to "flush out" weights. Maybe this will help find solution

**Comment by antis0007** [comment] 2023-05-22 18:16
Bumping this issue, will search for a solution in the code since this is still driving me crazy. Issue occurs when using lyco and lora at once in a prompt. Changing the prompt seems to have no effect and even after removing all loras or lycos, the lycoris remains loaded. This is a pretty significant issue because I can only fix it with a ui restart, and my gens will degrade under the same settings until I start to notice the glitchyness in the outputs. I made a character lyco that works great, I just cant use it with any other loras and its unfortunate.

**Comment by KohakuBlueleaf** [comment] 2023-05-26 03:07
@antis0007 I tried lot of pattern and still cannot reproduce this bug in my setup.
and I have tried on a entirely fresh installed sd-webui.

If you want a once and for all solution.
You just need to move all your lora/lycoris file into LyCORIS folder. and then turn off the built-in lora extension.

I am very sure this way you can avoid this kind of problem.

**Comment by magicFeirl** [comment] 2023-05-28 12:04
> @antis0007 I tried lot of pattern and still cannot reproduce this bug in my setup. and I have tried on a entirely fresh installed sd-webui.
> 
> If you want a once and for all solution. You just need to move all your lora/lycoris file into LyCORIS folder. and then turn off the built-in lora extension.
> 
> I am very sure this way you can avoid this kind of problem. I am also very sure that all the LoRAs that you can use in built-in lora, can use on my extesnion.

I turn off the built-in lora extension and some of my other extensions doesn't work anymore (also can't gen any image). The error is:
`ModuleNotFoundError: No module named 'lora'`

Error extensions:
stable-diffusion-webui-composable-lora
sd-webui-regional-prompter
stable-diffusion-webui-composable-lora
...

It seems like some extensions depend on the built-in lora, so we may can't simply turn off the built-in lora...

**Comment by KohakuBlueleaf** [comment] 2023-05-28 12:10
These extensions all hijack the built-in lora (just like what I have done with locon ext, and this will easily cause lot of error or hazard)

So yes, if you want to use other ext related to lora, you may not able to just turn it off.

**Comment by rehvka** [comment] 2023-06-03 05:22
well, I just updated auto1111 and now I face this issue too. I went back to the locon extension for a bit, since using lycoris keep frying my images :(

**Comment by KohakuBlueleaf** [comment] 2023-06-03 05:37
@rehvka Can you help me to check one thing?
I think there is an option like this:
![image](https://github.com/KohakuBlueleaf/a1111-sd-webui-lycoris/assets/59680068/803bcf20-8d0f-42b3-940c-190d36a97287)

do you have this enabled? or not?

**Comment by KohakuBlueleaf** [comment] 2023-06-03 05:37
I'm searching on a more robust way to do weight apply/restore
but I think my original way should be ok

**Comment by KohakuBlueleaf** [comment] 2023-06-03 05:54
@FNSpd @poko3347 @RayHell @BigBlueGX @antis0007 
I push a possible fix for this
I found a "maybe a bug" in my implementation
please help me to check if this is resolved

**Comment by KohakuBlueleaf** [comment] 2023-06-03 06:09
Wait, here is still some bugs
but I have idea for them

**Comment by rehvka** [comment] 2023-06-03 06:34
> @rehvka Can you help me to check one thing? I think there is an option like this: ![image](https://user-images.githubusercontent.com/59680068/243057142-803bcf20-8d0f-42b3-940c-190d36a97287.png)
> 
> do you have this enabled? or not?

I have it UNCHECKED, I did not even know this existed till you mentioned it :). I just saw you updated the extension, gonna try it and report results, Keep up the good work

**Comment by rehvka** [comment] 2023-06-03 06:46
Ok, I am back, problem is still there.

**Comment by KohakuBlueleaf** [comment] 2023-06-03 06:48
@FNSpd @poko3347 @RayHell @BigBlueGX @antis0007 @rehvka 
Finally I fixed it
![image](https://github.com/KohakuBlueleaf/a1111-sd-webui-lycoris/assets/59680068/6a70a299-ae6f-45a4-8abd-fffed865fdb7)
![image](https://github.com/KohakuBlueleaf/a1111-sd-webui-lycoris/assets/59680068/d9109f2d-f120-4ca4-8d03-82c14aecb870)

**Comment by KohakuBlueleaf** [comment] 2023-06-03 06:48
@rehvka please check it again
I have pushed a fix few sec before

**Comment by rehvka** [comment] 2023-06-03 07:26
okay, I did some testing! For the most part the issue seems to be gone! thank you so much! BUT.. I found a weird interaction when using 1 lora + 1 loha (through lycoris folder). If the lycoris is first, no problem at all but if you put lora first and lycoris second, it might fried the image. I didnt do a lot of testing cuz its late so this issue might be the interaction between those two loras or the model or both. But the original issue I think it is solved on my side. thank you @KohakuBlueleaf

**Comment by KohakuBlueleaf** [comment] 2023-06-03 07:33
@rehvka your "lora" is through <lora> or <lyco>?

**Comment by rehvka** [comment] 2023-06-03 07:39
> 

I dont think I understand. you mean if my lora went through? yes, it worked.

**Comment by KohakuBlueleaf** [comment] 2023-06-03 07:40
> > 
> 
> I dont think I understand. you mean if my lora went through? yes, it worked.

Sorry that I forgot github hate << and >>

I mean:

your "lora" is through <<lora>> or <<lyco>> ?

**Comment by rehvka** [comment] 2023-06-03 07:42
oh, I see, so.. if I use lets say  <lora:1.0> + <lyco:1.0> it might "burn" my images after several generations, but if I use <lyco:1.0> + <lora:1.0>, everything is fine.

**Comment by KohakuBlueleaf** [comment] 2023-06-03 07:46
@rehvka I think that is caused by other extension relate to lora or something like that
Since I really cannot reproduce this bug

**Comment by rehvka** [comment] 2023-06-03 07:48
yeah, it is a weird interaction, I wouldnt worry too much about it, thank you for the fix!

**Comment by KohakuBlueleaf** [comment] 2023-06-04 02:50
Since this issue is been resolved.
I will close this issue.
If there still any problem, just open new issue.

**Closed by KohakuBlueleaf** 2023-06-04 02:50 UTC
